### ISSUE TITLE
Outdated serialize-object.js causing issues

### ISSUE THREAD

**Issue by jaredatch** [CherryFramework/cherry-team-members#5]
Howdy,

Lead dev of WPForms here!

Currently our plugin does not function with Cherry Team Members.

There are two reasons for this:

- CTM loads it's assets across the entire admin - so right now assets are loading on pages where they aren't needed or used  (such as in our form builder)

- CTM loads an outdated version of serialized-object.js that is from 2013. Latest version is from 2015 (https://github.com/macek/jquery-serialize-object/blob/master/jquery.serialize-object.js).

What's happening is when the WPForms form builder loads, the `serialize-object` that we package isn't included because CTM has already loaded the outdated version globally. This causes an error because our builder is expecting the latest version that has additional features the outdated one does not.

Would be great if we could get this resolved in an upcoming update. Otherwise I'm going to have to include a hack in WPF that detects CTM and removes all the assets :)

**Comment by MjHead** [comment]
Hi @jaredatch! Thanks for report! Yes, we'll replace outdated version with new release in few days.

**Comment by jaredatch** [comment]
Much appreciated 😀

cheers!

**Comment by MjHead** [comment]
We fixed this issue and update plugin to 1.0.6. We add 'cherry' prefix to JS plugin and to WP handle to avoid any conflicts
